sudo: false
os:
  - linux

language: go

go:
    - 1.8

install:
  - make deps
  - gx-go rewrite

script:
  - gx test -v -race -coverprofile=coverage.txt -covermode=atomic .

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $GOPATH/src/gx
